services:
  - type: web
    name: campusiq
    runtime: python
    region: singapore
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python3 server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: N8N_WEBHOOK_URL
        value: https://n8n-tanmay.onrender.com/webhook/campusiq-notices
      - key: EDUMARSHAL_USERNAME
        value: 08414802725
      - key: EDUMARSHAL_PASSWORD
        value: mait@2029
      - key: DATABASE_URL
        fromDatabase:
          name: campusiq-db
          property: connectionString
      - key: ENCRYPTION_KEY
        generateValue: true

databases:
  - name: campusiq-db
    plan: free
    region: singapore
    databaseName: campusiq
    user: campusiq


